### ISSUE TITLE
NgOverlayContainerService Provider Breaks for Child Modules

### ISSUE THREAD

**Issue by dereekb** [schulzi66/ng-overlay-container#7]
Hi,

I ran into an issue where the Injector being used comes from the app's Root module instead of the more relevant module, causing injection issues and dependencies not being found.

I am using lazy-loaded modules, using UIRouter but as far as I understand they work the same way described [here](https://angular.io/guide/lazy-loading-ngmodules).

The expected behavior would be more like MatDialog, where the Injector is set to the module it is being referenced from.

Here's a screenshot of the different injectors at runtime. The first one is MatDialog and it's referenced Injector, the second is Injector directly injected, and the third is the injector being used by the NgOverlayContainerService. SecureModule is the child lazy-loaded module, and AppModule is the root module.

![Screen Shot 2021-04-20 at 12 51 04 AM](https://user-images.githubusercontent.com/3586580/115344260-ba5e0680-a172-11eb-9d32-d444d8fd804c.png)

I "think" the issue is related to ProvidedIn being set for the service.

https://github.com/schulzi66/ng-overlay-container/blob/8a6e695715ce146d922940ab6b3fee17357d1103/projects/ng-overlay-container/src/lib/ng-overlay-container.service.ts#L18

Where as MatDialog omits it:

https://github.com/angular/components/blob/94ea13cc195b4c3d318591a7ad83a3515e94f156/src/material/dialog/dialog.ts#L391

MatDialog is provided by the MatDialogModule instead of the root:

https://github.com/angular/components/blob/ad248652e7da31398176fe11878b59805e440b5a/src/material-experimental/mdc-dialog/module.ts#L44

If you remove ProvidedIn and add it to the NgOverlayContainerModule I think it should use the proper injector, so an instance will be created when needed (as far as I understand).

For now my workaround is just creating a new service that wraps NgOverlayContainerService.

```
@Injectable()
export class AppStickyPopupService {

  private _overlayContainerService: NgOverlayContainerService;

  constructor(private _overlay: Overlay, private _injector: Injector) {
    this._overlayContainerService = new NgOverlayContainerService(this._overlay, this._injector);
  }

```

And in the module:

```
@NgModule({
  imports: [
    CommonModule,
    MatIconModule,
    MatButtonModule,
    AppAnchorModule,
    NgOverlayContainerModule
  ],
  declarations: [],
  exports: [],
  providers: [
    AppStickyPopupService
  ]
})
export class AppStickyPopupModule {}
```

**Comment by schulzi66** [comment]
Hey @dereekb,
thank you for your feedback! Yes that seems to be an issue indeed. I will take care of this later. Otherwise feel free to create a PR 👍

**Comment by schulzi66** [comment]
@dereekb Feel free to check out the new version 11.0.2 and give feedback if you are still facing issues.

**Comment by dereekb** [comment]
That was fast, thanks!
